version: '3.7'

services:
    
  gitclone:
    image: gitclone
    depends_on:
      - gitclone_db
    container_name: gitclone
    ports: 
      - "1001:80"
    build:
      context: GitClone
      dockerfile: Dockerfile
    networks:
      - dev

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "2001:80"
    build:
      context: Frontend
      dockerfile: Dockerfile

  clonerepo_db:
    image: postgres:latest
    container_name: gitclone_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev

networks:
  dev:
    driver: bridge 

volumes:
  customer_data:
  pgadmin: